
--Pedir_ventas_fecha--
SELECT VABRDO,TIDO,NUDO,FEEMDO,HORAGRAB FROM MAEEDO
WHERE ENDO = ?
AND FEEMDO >= ?
AND (TIDO = ? OR TIDO = ? OR TIDO = ?);

--Pedir_pagos_dia--
SELECT VADP,FEEMDP FROM MAEDPCE
WHERE DOCUENANTI = ?;

--Pedir_nudo--
SELECT TIDO,NUDO,FEEMDO,VABRDO FROM MAEEDO
WHERE NUDO = ?;